language: php

php:
  - 7
  - 7.1

before_script:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/codecept run unit --coverage-xml

after_script:
  - ./vendor/bin/ocular code-coverage:upload --format=php-clover tests/_output/coverage.xml

notifications:
  irc: "irc.freenode.org#fuelphp-status"
